### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/apdcephfs/share_1290939/feiiyin/TH/PIRender_bak/Deep3DFaceRecon_pytorch/BFM/01_MorphableModel.mat'

### ISSUE THREAD

**Issue by jeminteza08** [FeiiYin/SPI#1]
!python preprocess/run_total.py --input_root=input_root --output_root=output_root --mode=jpg

![image](https://github.com/FeiiYin/SPI/assets/143048730/367be7cf-7215-4fa1-8580-852e138cc399)

----------------- Options ---------------
                add_image: True                          
               bfm_folder: /apdcephfs/share_1290939/feiiyin/TH/PIRender_bak/Deep3DFaceRecon_pytorch/BFM/	[default: BFM]
                bfm_model: BFM_model_front.mat           
                 camera_d: 10.0                          
                   center: 112.0                         
          checkpoints_dir: /apdcephfs/share_1290939/feiiyin/TH/PIRender_bak/Deep3DFaceRecon_pytorch/checkpoints	[default: ./checkpoints]
             dataset_mode: None                          
                 ddp_port: 12355                         
        display_per_batch: True                          
                    epoch: 20                            	[default: latest]
          eval_batch_nums: inf                           
                    focal: 1015.0                        
                  gpu_ids: 0                             
               img_folder: temp                          	[default: examples]
                init_path: checkpoints/init_model/resnet50-0676ba61.pth
                  isTrain: False                         	[default: None]
                    model: facerecon                     
                     name: model_name                    	[default: face_recon]
                net_recon: resnet50                      
                    phase: test                          
                   suffix:                               
                  use_ddp: False                         	[default: True]
              use_last_fc: False                         
                  verbose: False                         
           vis_batch_nums: 1                             
               world_size: 1                             
                    z_far: 15.0                          
                   z_near: 5.0                           
----------------- End -------------------
Transfer BFM09 to BFM_model_front......
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/apdcephfs/share_1290939/feiiyin/TH/PIRender_bak/Deep3DFaceRecon_pytorch/BFM/01_MorphableModel.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/SPI/preprocess/run_total.py", line 92, in <module>
    main()
  File "/content/SPI/preprocess/run_total.py", line 38, in main
    extractor = CameraExtractor(crop_outdir=None, c_outdir=None, mode=None)
  File "/content/SPI/preprocess/extract_camera.py", line 57, in __init__
    self.model_3dmm = Extract3dmm({
  File "/content/SPI/preprocess/extract_3dmm.py", line 119, in __init__
    self.model = create_model(opt)
  File "/content/SPI/third_part/Deep3DFaceRecon_pytorch/models/__init__.py", line 66, in create_model
    instance = model(opt)
  File "/content/SPI/third_part/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 92, in __init__
    self.facemodel = ParametricFaceModel(
  File "/content/SPI/third_part/Deep3DFaceRecon_pytorch/models/bfm.py", line 40, in __init__
    transferBFM09(bfm_folder)
  File "/content/SPI/third_part/Deep3DFaceRecon_pytorch/util/load_mats.py", line 34, in transferBFM09
    original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
  File "/usr/local/lib/python3.10/dist-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/usr/local/lib/python3.10/dist-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/apdcephfs/share_1290939/feiiyin/TH/PIRender_bak/Deep3DFaceRecon_pytorch/BFM/01_MorphableModel.mat'

**Comment by johnren-code** [comment]
have you solved it?

**Comment by FeiiYin** [comment]
Sorry for my mistake. To pre-process the data, we employ 3dmm tools to estimate the camera pose. The pretrained models can be download from the links of https://drive.google.com/drive/folders/1-m47oPsa3kxjgK5eSJ8g8sHzG4zr2oRc?usp=sharing, which is the pre-trained models of StyleHEAT(https://github.com/OpenTalker/StyleHEAT).

**Comment by FeiiYin** [comment]
Feel free to re-open this issue. :-)
